flags:
  ac: 'Flag of Ascension Island'
  ad: 'Flag of Andorra'
  ae: 'Flag of the United Arab Emirates'
  af: 'Flag of Afghanistan'
  ag: 'Flag of Antigua and Barbuda'
  ai: 'Flag of Anguilla'
  al: 'Flag of Albania'
  am: 'Flag of Armenia'
  an: 'Flag of the Netherlands Antilles'
  ao: 'Flag of Angola'
  aq: 'Flags of Antarctica'
  ar: 'Flag of Argentina'
  ara: 'Arabic language icon: Green flag with first letter of Arabic alphabet'
  as: 'Flag of American Samoa'
  at: 'Flag of Austria'
  au: 'Flag of Australia'
  aw: 'Flag of Aruba'
  ax: 'Flag of Åland'
  az: 'Flag of Azerbaijan'
  ba: 'Flag of Bosnia and Herzegovina'
  bb: 'Flag of Barbados'
  bd: 'Flag of Bangladesh'
  be: 'Flag of Belgium'
  bf: 'Flag of Burkina Faso'
  bg: 'Flag of Bulgaria'
  bh: 'Flag of Bahrain'
  bi: 'Flag of Burundi'
  bj: 'Flag of Benin'
  bl: 'Flag of Saint Barthelemy'
  bm: 'Flag of Bermuda'
  bn: 'Flag of Brunei'
  bo: 'Flag of Bolivia'
  bod: 'Flag of Tibet'
  br: 'Flag of Brazil'
  bs: 'Flag of the Bahamas'
  bt: 'Flag of Bhutan'
  bw: 'Flag of Botswana'
  by: 'Flag of Belarus'
  bz: 'Flag of Belize'
  ca: 'Flag of Canada'
  cc: 'Flag of the Cocos (Keeling) Islands'
  cd: 'Flag of the Democratic Republic of the Congo'
  cf: 'Flag of the Central African Republic'
  cg: 'Flag of the Republic of the Congo'
  ch: 'Flag of Switzerland'
  ci: 'Flag of Ivory Coast'
  ck: 'Flag of the Cook Islands'
  cl: 'Flag of Chile'
  cm: 'Flag of Cameroon'
  cn: 'Flag of China'
  co: 'Flag of Colombia'
  cr: 'Flag of Costa Rica'
  crs-io: 'Flag of the Chagossians community'
  cu: 'Flag of Cuba'
  cv: 'Flag of Cape Verde'
  cw: 'Flag of Curaçao'
  cx: 'Flag of Christmas Island'
  cy: 'Flag of Cyprus'
  cz: 'Flag of the Czech Republic'
  de: 'Flag of Germany'
  dj: 'Flag of Djibouti'
  dk: 'Flag of Denmark'
  dm: 'Flag of Dominica'
  do: 'Flag of the Dominican Republic'
  dz: 'Flag of Algeria'
  ec: 'Flag of Ecuador'
  ee: 'Flag of Estonia'
  eg: 'Flag of Egypt'
  eh: 'Flag of Western Sahara'
  epo: 'The Esperanto Flag'
  er: 'Flag of Eritrea'
  es: 'Flag of Spain'
  es-as: 'Flag of Asturias'
  es-ct: 'Flag of Catalonia'
  es-ga: 'Flag of Galicia'
  eu: 'Flag of Europe'
  eus: 'The Basque flag'
  et: 'Flag of Ethiopia'
  fi: 'Flag of Finland'
  fj: 'Flag of Fiji'
  fk: 'Flag of the Falkland Islands'
  fm: 'Flag of the Federated States of Micronesia'
  fo: 'Flag of the Faroe Islands'
  fr: 'Flag of France'
  ga: 'Flag of Gabon'
  gb: 'Flag of the United Kingdom'
  gb-eng: 'Flag of England'
  gb-sct: 'Flag of Scotland'
  gb-wls: 'Flag of Wales'
  gd: 'Flag of Grenada'
  ge: 'Flag of Georgia'
  gf: 'Flag of French Guiana'
  gg: 'Flag of Guernsey'
  gh: 'Flag of Ghana'
  gi: 'Flag of Gibraltar'
  gl: 'Flag of Greenland'
  gm: 'Flag of the Gambia'
  gn: 'Flag of Guinea'
  gq: 'Flag of Equatorial Guinea'
  gr: 'Flag of Greece'
  gs: 'Flag of South Georgia and the South Sandwich Islands'
  gt: 'Flag of Guatemala'
  gu: 'Flag of Guam'
  gw: 'Flag of Guinea-Bissau'
  gy: 'Flag of Guyana'
  hk: 'Flag of Hong Kong'
  hn: 'Flag of Honduras'
  hr: 'Flag of Croatia'
  ht: 'Flag of Haiti'
  hu: 'Flag of Hungary'
  id: 'Flag of Indonesia'
  ie: 'Flag of Ireland'
  il: 'Flag of Israel'
  im: 'Flag of the Isle of Man'
  in: 'Flag of India'
  io: 'Flag of British Indian Ocean Territory'
  iq: 'Flag of Iraq'
  ir: 'Flag of Iran'
  is: 'Flag of Iceland'
  it: 'Flag of Italy'
  je: 'Flag of Jersey'
  jm: 'Flag of Jamaica'
  jo: 'Flag of Jordan'
  jp: 'Flag of Japan'
  ke: 'Flag of Kenya'
  kg: 'Flag of Kyrgyzstan'
  kh: 'Flag of Cambodia'
  ki: 'Flag of Kiribati'
  km: 'Flag of the Comoros'
  kn: 'Flag of Saint Kitts and Nevis'
  kp: 'Flag of North Korea'
  kr: 'Flag of South Korea'
  kur: 'Flag of Kurdistan'
  kw: 'Flag of Kuwait'
  ky: 'Flag of Cayman Islands'
  kz: 'Flag of Kazakhstan'
  la: 'Flag of Laos'
  lb: 'Flag of Lebanon'
  lc: 'Flag of Saint Lucia'
  li: 'Flag of Liechtenstein'
  lk: 'Flag of Sri Lanka'
  lr: 'Flag of Liberia'
  ls: 'Flag of Lesotho'
  lt: 'Flag of Lithuania'
  lu: 'Flag of Luxembourg'
  lv: 'Flag of Latvia'
  ly: 'Flag of Libya'
  ma: 'Flag of Morocco'
  mc: 'Flag of Monaco'
  md: 'Flag of Moldova'
  me: 'Flag of Montenegro'
  mg: 'Flag of Madagascar'
  mh: 'Flag of Marshall Islands'
  mk: 'Flag of Macedonia'
  ml: 'Flag of Mali'
  mm: 'Flag of Myanmar / Burma'
  mn: 'Flag of Mongolia'
  mo: 'Flag of Macau'
  mp: 'Flag of the Northern Mariana Islands'
  mq: 'Flag of Martinique'
  mr: 'Flag of Mauritania'
  ms: 'Flag of Montserrat'
  mt: 'Flag of Malta'
  mu: 'Flag of Mauritius'
  mv: 'Flag of the Maldives'
  mw: 'Flag of Malawi'
  mx: 'Flag of Mexico'
  my: 'Flag of Malaysia'
  mz: 'Flag of Mozambique'
  na: 'Flag of Namibia'
  nc: 'Flag of New Caledonia'
  ne: 'Flag of Niger'
  nf: 'Flag of Norfolk Island'
  ng: 'Flag of Nigeria'
  ni: 'Flag of Nicaragua'
  nl: 'Flag of the Netherlands'
  nl-fy: 'Flag of Friesland'
  'no': 'Flag of Norway'
  np: 'Flag of Nepal'
  nr: 'Flag of Nauru'
  nu: 'Flag of Niue'
  nz: 'Flag of New Zealand'
  oci: 'The Occitan cross'
  om: 'Flag of Oman'
  pa: 'Flag of Panama'
  pe: 'Flag of Peru'
  pf: 'Flag of French Polynesia'
  pg: 'Flag of Papua New Guinea'
  ph: 'Flag of the Philippines'
  pk: 'Flag of Pakistan'
  pl: 'Flag of Poland'
  pm: 'Flag of Saint Pierre and Miquelon'
  pn: 'Flag of the Pitcairn Islands'
  pr: 'Flag of Puerto Rico'
  ps: 'Flag of Saint Lucia'
  pt: 'Flag of Portugal'
  pw: 'Flag of Palau'
  py: 'Flag of Paraguay'
  qa: 'Flag of Qatar'
  ro: 'Flag of Romania'
  rs: 'Flag of Serbia'
  ru: 'Flag of Russia'
  rw: 'Flag of Rwanda'
  sa: 'Flag of Saudi Arabia'
  sb: 'Flag of the Solomon Islands'
  sc: 'Flag of Seychelles'
  sd: 'Flag of Sudan'
  se: 'Flag of Sweden'
  sg: 'Flag of Singapore'
  sh: 'Flag of Saint Helena'
  si: 'Flag of Slovenia'
  sk: 'Flag of Slovakia'
  sl: 'Flag of Sierra Leone'
  sm: 'Flag of San Marino'
  sme: 'Sami flag'
  sn: 'Flag of Senegal'
  so: 'Flag of Somalia'
  sr: 'Flag of Suriname'
  ss: 'Flag of South Sudan'
  st: 'Flag of São Tomé and Príncipe'
  sv: 'Flag of El Salvador'
  sx: 'Flag of Sint Maarten'
  sy: 'Flag of Syria'
  sz: 'Flag of Swaziland'
  ta: 'Flag of Tristan da Cunha'
  tam: 'Sri Lankan Tamil Ethnic flag'
  tc: 'Flag of the Turks and Caicos Islands'
  td: 'Flag of Chad'
  tf: 'Flag of French Southern and Antarctic Lands'
  tg: 'Flag of Togo'
  th: 'Flag of Thailand'
  tj: 'Flag of Tajikistan'
  tk: 'Flag of Tokelau'
  tl: 'Flag of East Timor'
  tm: 'Flag of Turkmenistan'
  tn: 'Flag of Tunisia'
  to: 'Flag of Tonga'
  tr: 'Flag of Turkey'
  tt: 'Flag of Trinidad and Tobago'
  tv: 'Flag of Tuvalu'
  tw: 'Flag of Taiwan'
  tyv: 'Flag of Tuvalu'
  tz: 'Flag of Tanzania'
  ua: 'Flag of Ukraine'
  ug: 'Flag of Uganda'
  uig: 'Flag of East Turkestan'
  un: 'Flag of the United Nations'
  us: 'Flag of the United States'
  uy: 'Flag of Uruguay'
  uz: 'Flag of Uzbekistan'
  va: 'Flag of Vatican City'
  vc: 'Flag of Saint Vincent and the Grenadines'
  ve: 'Flag of Venezuela'
  vg: 'Flag of the British Virgin Islands'
  vi: 'Flag of the United States Virgin Islands'
  vn: 'Flag of Vietnam'
  vu: 'Flag of Vanuatu'
  wf: 'Flag of Wallis and Futuna'
  ws: 'Flag of Samoa'
  ye: 'Flag of Yemen'
  yt: 'Flag of Mayotte'
  za: 'Flag of South Africa'
  zm: 'Flag of Zambia'
  zw: 'Flag of Zimbabwe'
_core:
  default_config_hash: At3Dj83sLY6f7B29d9WAWH_xLaP46wbCETEfuwfl8nw
